@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Guitar {
- serialNumber: String
- price : double
- builder : Builder
- model : String
- type : Type
- backWood : Wood
- topWood : Wood


}
Class Inventory{
}
Inventory o-- Guitar

enum Type{
    ELECTRIC
    ACOUSTIC
}

enum Wood{
    CEDAR
    ALDER
    MAHOGANY
}

enum Builder{
    FENDER
    COLLINS
    WILSON
    YAMAHA
}

@enduml