@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Manager {
    - {static} String manID
    - String sName
    - String fName
}

class Staff {
    - {static} staffID
    - String sName
    - String fName
    - String telNo
}

class Branch {
    - {static} String bNo
    - String fName
    - String telNo
}

Staff <-- Manager : is A
Staff "1...*" --o Branch : allocated
Manager --o "1...3" Branch : manages

@enduml