@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Question {
    -String text;
    -String answer;

    +display() :void
    +checkAnswer(String) : boolean
}

class Quiz {
    -Question
}

Quiz *--"1..*" Question : contains

@enduml