@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Dice {
    -int faceValue

    +int roll()
}

class Player {

    + isWinner() : Boolean
}

Player *--"2" Dice : requires

@enduml