@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Dice {
    -int sides

    +int roll()
}

class Player {
    - {}static} id
    - Dice dice1
    - Dice dice2

    + isWinner()
}

Player "1..2"*-- Dice

@enduml